$(document).ready(function() {
			var preloadImages = ['images/1940_a RH 3rd from Right_Front Row.jpg','images/1940_b RH Bhadarsa 1940s RH 3rd from Right_Front Row.jpg','images/1952 RH Allahabad.jpg','images/1953 RH bachelor degree.jpg','images/1954a Dada Dadda SH ZH RH ZS.jpg','images/1954b RH Lahore.jpg','images/1954c RH Shalimar.jpg','images/1957 Seemi RH LHR.jpg','images/1958 RH portrait.jpg','images/1959 Family Photo.jpg','images/1960a RH portrait.jpg','images/1960b RH ZS.jpg','images/1964a RH Beena.jpg','images/1964b RH friend wedding.jpg','images/1965 RH Sehba.jpg','images/1967 RH_WH_SH_NH.jpg','images/1968a Family.jpg','images/1968b RH MAKH first PK trip together.jpg','images/1970_a RH.jpg','images/1970_b RH MAKH.jpg','images/1975 MAKH, RH, US & ZS.jpg','images/1976 RH, MAKH, NEH.jpg','images/1977a MN, RH.jpg',	'images/1977b RH, MH, NEH and WH.jpg',	'images/1981a RH, ZH, WH.jpg','images/1981b RH.jpg','images/1982a RH, ZH, SH.jpg','images/1982b RH, ZH, SH, NEH.jpg','images/1982c RH & ZS.jpg','images/1982d RH.jpg','images/1982e RH, MAKH.jpg','images/1982f RH Mermaid.jpg','images/1982g RH, ZS, NEH.jpg',	'images/1983 RH & ZS.jpg','images/1984 RH & MAKH Rock.jpg',	'images/1985 RH Beach.jpg','images/1987a RH Hong Kong.jpg','images/1987br RH Hong Kong.jpg','images/1988a MAKH RH Killara garden.jpg','images/1988b RH Killara garden.jpg','images/1992 RH & MAKH Singapore.jpg','images/1996a RH & Arthur Delbridge.jpg','images/1996b Imamul, ZS, MS, RH.jpg','images/1999a RH, NEH, SM, MAKH wedding.jpg','images/1999b RH, SM, ZS wedding.jpg','images/1999c MAKH, RH wedding.jpg','images/2003 RH & SS Dorrigo.jpg','images/2008 RH Queenslander.jpg','images/2009a Hong Kong General.jpg','images/2009b RH & MAKH.jpg','images/2009c Beijing General.jpg','images/2009d Multan conference general.jpg','images/2009e RH, ZS Multan RH-ZS.jpg','images/2010a RH, MAKH, JW.jpg','images/2010b GW, RH.jpg','images/2011a MS, RH, MAKH, TS Hong Kong.jpg','images/2011b MAKH, RH, TS Hong Kong.jpg','images/2012 AL, RH.jpg','images/2012 RH ZS.jpg','images/2013a RH, MAKH, Others ISFC.jpg','images/2013b ISFC conference general.jpg','images/2013c RH Hong Kong.jpg','images/2013d RH, MAKH, NEH, NCH & AS.jpg','images/2014a SS, MS & RH.jpg','images/2014b RH, BS.jpg','images/2014c August 26 RH BS AD NEH Legal Seafood 2.jpg','images/2014d August 26 RH NEH BS Nespresso Cafe.jpg','images/2014e RH steam train.jpg','images/2014f RH with SalS.jpg','images/2014g RH SH.jpg','images/2014h RH with Mo Shuet.jpg','images/2014i RH NEH.jpg','images/2014j RH and SH.JPG','images/2014k RH & JL Biltmore.jpg','images/2014l Family Pakistan.jpg','images/2014m RH.jpg','images/2014n NEH, AvHD, SM, AsHD, THD, RH, MAKH.jpg','images/2015a RH, MAKH, KS, TS.jpg','images/2015b RH & MAKH.jpg'];
			var imgs = [];
			for (var i=0; i<preloadImages.length;i++) {
				imgs[i] = new Image();
				imgs[i].src = preloadImages[i];
			}
			
			images1 = '<div id="photos" style="display:none"><img src="images/1940_a RH 3rd from Right_Front Row.jpg" alt="Slide 1" id="firstIMG"/><img src="images/1940_b RH Bhadarsa 1940s RH 3rd from Right_Front Row.jpg" alt="Slide 2" /><img src="images/1952 RH Allahabad.jpg" alt="Slide 3" /> <img src="images/1953 RH bachelor degree.jpg" alt="Slide 4" /><img src="images/1954a Dada Dadda SH ZH RH ZS.jpg" alt="Slide 5" /><img src="images/1954b RH Lahore.jpg" alt="Slide 6" /><img src="images/1954c RH Shalimar.jpg" alt="Slide 7" /><img src="images/1957 Seemi RH LHR.jpg" alt="Slide 8" /><img src="images/1958 RH portrait.jpg" alt="Slide 9" /><img src="images/1959 Family Photo.jpg" alt="Slide 10" />';
			images2 = '<img src="images/1960a RH portrait.jpg" alt="Slide 11" /><img src="images/1960b RH ZS.jpg" alt="Slide 12" /><img src="images/1964a RH Beena.jpg" alt="Slide 13" /><img src="images/1964b RH friend wedding.jpg" alt="Slide 14" /><img src="images/1965 RH Sehba.jpg" alt="Slide 15" /> <img src="images/1967 RH_WH_SH_NH.jpg" alt="Slide 16" /><img src="images/1968a Family.jpg" alt="Slide 17" /><img src="images/1968b RH MAKH first PK trip together.jpg" alt="Slide 18" /><img src="images/1970_a RH.jpg" alt="Slide 19" /><img src="images/1970_b RH MAKH.jpg" alt="Slide 20" />';
			images3 = '<img src="images/1975 MAKH, RH, US & ZS.jpg" alt="Slide 21" /><img src="images/1976 RH, MAKH, NEH.jpg" alt="Slide 22" /><img src="images/1977a MN, RH.jpg" alt="Slide 23" /><img src="images/1977b RH, MH, NEH and WH.jpg" alt="Slide 24" /><img src="images/1981a RH, ZH, WH.jpg" alt="Slide 25" /><img src="images/1981b RH.jpg" alt="Slide 26" /><img src="images/1982a RH, ZH, SH.jpg" alt="Slide 27" />    <img src="images/1982b RH, ZH, SH, NEH.jpg" alt="Slide 28" /><img src="images/1982c RH & ZS.jpg" alt="Slide 29" /><img src="images/1982d RH.jpg" alt="Slide 30" />';
			images4 = '<img src="images/1982e RH, MAKH.jpg" alt="Slide 31" /> <img src="images/1982f RH Mermaid.jpg" alt="Slide 32" /><img src="images/1982g RH, ZS, NEH.jpg" alt="Slide 33" /><img src="images/1983 RH & ZS.jpg" alt="Slide 34" /><img src="images/1984 RH & MAKH Rock.jpg" alt="Slide 35" /> <img src="images/1985 RH Beach.jpg" alt="Slide 36" /><img src="images/1987a RH Hong Kong.jpg" alt="Slide 37" /><img src="images/1987br RH Hong Kong.jpg" alt="Slide 38" /><img src="images/1988a MAKH RH Killara garden.jpg" alt="Slide 39" /> <img src="images/1988b RH Killara garden.jpg" alt="Slide 40" />';
			images5 = '<img src="images/1992 RH & MAKH Singapore.jpg" alt="Slide 41" /><img src="images/1996a RH & Arthur Delbridge.jpg" alt="Slide 42" /><img src="images/1996b Imamul, ZS, MS, RH.jpg" alt="Slide 43" /><img src="images/1999a RH, NEH, SM, MAKH wedding.jpg" alt="Slide 44" /<img src="images/1999b RH, SM, ZS wedding.jpg" alt="Slide 45" /><img src="images/1999c MAKH, RH wedding.jpg" alt="Slide 46" /><img src="images/2003 RH & SS Dorrigo.jpg" alt="Slide 47" />  <img src="images/2008 RH Queenslander.jpg" alt="Slide 48" /><img src="images/2009a Hong Kong General.jpg" alt="Slide 49" /><img src="images/2009b RH & MAKH.jpg" alt="Slide 50" />';
			images6 = '<img src="images/2009c Beijing General.jpg" alt="Slide 51" /><img src="images/2009d Multan conference general.jpg" alt="Slide 52" /><img src="images/2009e RH, ZS Multan RH-ZS.jpg" alt="Slide 53" /><img src="images/2010a RH, MAKH, JW.jpg" alt="Slide 54" /><img src="images/2010b GW, RH.jpg" alt="Slide 55" /><img src="images/2011a MS, RH, MAKH, TS Hong Kong.jpg" alt="Slide 56" /><img src="images/2011b MAKH, RH, TS Hong Kong.jpg" alt="Slide 57" /><img src="images/2012 AL, RH.jpg" alt="Slide 58" /><img src="images/2012 RH ZS.jpg" alt="Slide 59" /> <img src="images/2013a RH, MAKH, Others ISFC.jpg" alt="Slide 60" />';
			images7 = '<img src="images/2013b ISFC conference general.jpg" alt="Slide 61" /><img src="images/2013c RH Hong Kong.jpg" alt="Slide 62" /><img src="images/2013d RH, MAKH, NEH, NCH & AS.jpg" alt="Slide 63" /><img src="images/2014a SS, MS & RH.jpg" alt="Slide 64" /><img src="images/2014b RH, BS.jpg" alt="Slide 65" /><img src="images/2014c August 26 RH BS AD NEH Legal Seafood 2.jpg" alt="Slide 66" /><img src="images/2014d August 26 RH NEH BS Nespresso Cafe.jpg" alt="Slide 67" /><img src="images/2014e RH steam train.jpg" alt="Slide 68" /><img src="images/2014f RH with SalS.jpg" alt="Slide 69" />    <img src="images/2014g RH SH.jpg" alt="Slide 70" />';
			images8 = '<img src="images/2014h RH with Mo Shuet.jpg" alt="Slide 71" /><img src="images/2014i RH NEH.jpg" alt="Slide 72" /><img src="images/2014j RH and SH.jpg" alt="Slide 73" /> <img src="images/2014k RH & JL Biltmore.jpg" alt="Slide 74" /<img src="images/2014l Family Pakistan.jpg" alt="Slide 75" />  <img src="images/2014m RH.jpg" alt="Slide 76" /><img src="images/2014n NEH, AvHD, SM, AsHD, THD, RH, MAKH.jpg" alt="Slide 77" /><img src="images/2015a RH, MAKH, KS, TS.jpg" alt="Slide 78" /><img src="images/2015b RH & MAKH.jpg" alt="Slide 79" /></div>';
			$("#slideShowImages").append(images1+images2+images3+images4+images5+images6+images7+images8);
				
			$("#photos").show();
			
			$("#msg").hide();
			
			if (screen.width < 780) {
				$("#slideStyle").attr('src', 'slideShow_mobile.js');
			}
			else {
				$("#slideStyle").attr('src', 'slideShow.js');
				$("#slideShowImages").css({"position":"relative"});
			}	
		}); //end ready